### ISSUE TITLE
应该增加无用singleUploader对象的注销机制

### ISSUE THREAD

**Issue by bh-lay** [bh-lay/uploader#1]
每次创建完singleUploader后，若未进行上传操作，singleUploader会一直留存在dom及内存中，需要在合适的时候将其注销掉！

**Comment by sundyxfan** [comment]
在chrome 42 版本和火狐浏览器中不能正常使用

**Comment by bh-lay** [comment]
这么严重，我来测试一下！

**Comment by sundyxfan** [comment]
嗯

**Comment by sundyxfan** [comment]
hi  修复了吗

**Comment by bh-lay** [comment]
呃，你用的是 mac 么，貌似我在 windows 下没能重现你描述的问题！

**Comment by zmofei** [comment]
目录里放一个demo吧，这样别人clone之后就能直接看效果

**Comment by bh-lay** [comment]
这个比较特殊，因为是上传，必须配有对应的后台接口，so demo 的事你懂得！

**Comment by sundyxfan** [comment]
是用的Mac  为啥Mac 下出现这个？

**Comment by bh-lay** [comment]
呃，只是 windows 下没有重现，猜测是不是 Mac 下的 bug，看来我要厚着脸皮去借台 Mac 了！

**Comment by sundyxfan** [comment]
不知出错在哪里

**Comment by sundyxfan** [comment]
页面上是有多个上传按钮，定义一个class ,然后dom: $('.loadfile'),这样初始化的

**Comment by bh-lay** [comment]
跪舔好友，求到了一台Mac，问题目前已解决！
